package com.starnet.core.domain

object UkrainianTranslator {
    private val glossary = linkedMapOf(
        "Knowledge base loaded from local seed." to "Базу знань завантажено з локального seed-файлу.",
        "Sync in progress..." to "Синхронізація виконується...",
        "Sync failed" to "Помилка синхронізації",
        "Knowledge base synced to revision" to "Базу знань синхронізовано до ревізії",
        "AI local mode enabled. Cloud lookup optional." to "Локальний AI режим увімкнено. Cloud-пошук необов'язковий.",
        "Cloud lookup URL is empty. AI local mode is still active." to "URL cloud-пошуку порожній. Локальний AI режим продовжує працювати.",
        "Checking cloud lookup server..." to "Перевірка cloud-сервера пошуку...",
        "Cloud lookup server ready (revision" to "Cloud-сервер пошуку доступний (ревізія",
        "Cloud lookup unavailable, using AI local mode" to "Cloud-пошук недоступний, використовується локальний AI режим",
        "AI local diagnosis for" to "Локальна AI-діагностика для",
        "Detected CNC controller screen." to "Виявлено екран ЧПУ контролера.",
        "Detected machine nameplate" to "Виявлено табличку (nameplate) верстата",
        "Detected electrical schematic content." to "Виявлено електричну схему.",
        "Detected hydraulic scheme/context." to "Виявлено гідравлічну схему.",
        "Detected engineering drawing-style annotations." to "Виявлено анотації інженерного креслення.",
        "Image analyzed. Manual review recommended." to "Зображення проаналізовано. Рекомендована ручна перевірка.",
        "Possible causes" to "Можливі причини",
        "Step-by-step checks" to "Покрокова перевірка",
        "No diagnosis yet." to "Діагностика ще не виконана.",
        "No image analyzed yet." to "Зображення ще не проаналізовано.",
        "No alarm signature matched." to "Сигнатуру alarm не знайдено.",
        "manual input" to "ручне введення",
        "Invalid values." to "Некоректні значення.",
        "No points generated." to "Точки ще не згенеровано.",
        "Workpiece clamped" to "Заготовка затиснута",
        "Tool setup verified" to "Налаштування інструменту перевірено",
        "Offsets entered" to "Корекції введені",
        "Work zero confirmed" to "Нуль деталі підтверджено",
        "Program reviewed" to "Програму перевірено",
        "Dry run completed" to "Dry Run виконано",
        "Single block test completed" to "Перевірку Single Block виконано",
        "Axis overload or mechanical binding" to "Перевантаження осі або механічне заклинювання",
        "Encoder/feedback issue" to "Проблема енкодера або зворотного зв'язку",
        "Amplifier ready/power chain issue" to "Проблема ланцюга готовності або живлення підсилювача",
        "Check alarm history and axis suffix" to "Перевірте історію alarm і суфікс осі",
        "Inspect axis movement, lubrication, and brake" to "Перевірте рух осі, мастило та гальмо",
        "Check drive/encoder cables and servo amplifier status LEDs" to "Перевірте кабелі приводу/енкодера та індикатори сервопідсилювача",
        "Spindle load too high" to "Занадто велике навантаження шпинделя",
        "Spindle amplifier communication fault" to "Збій зв'язку зі шпиндельним підсилювачем",
        "Position coder mismatch or cable issue" to "Невідповідність позиційного датчика або проблема кабелю",
        "Reduce load and retry low-speed test" to "Зменште навантаження і повторіть тест на малих обертах",
        "Verify spindle amp alarms and cable integrity" to "Перевірте alarm шпиндельного підсилювача та цілісність кабелів",
        "Check spindle orientation/coder parameters" to "Перевірте орієнтацію шпинделя і параметри датчика",
        "Program format/modality error" to "Помилка формату або модальності програми",
        "Unsupported option command" to "Команда недоступної опції",
        "Parameter/state mismatch" to "Невідповідність параметрів або стану",
        "Locate offending block on alarm screen" to "Знайдіть проблемний блок на екрані alarm",
        "Verify postprocessor/control variant" to "Перевірте постпроцесор і варіант контролера",
        "Check recent parameter changes then reset" to "Перевірте останні зміни параметрів і виконайте скидання",
        "Soft/hard limit exceeded" to "Перевищено м'який або жорсткий ліміт ходу",
        "Incorrect work offset/tool offset" to "Некоректний робочий нуль або корекція інструменту",
        "Wrong reference return state" to "Неправильний стан повернення в референс",
        "Jog out in safe direction" to "Виведіть вісь джогом у безпечному напрямку",
        "Check G54/offsets and stroke limit params" to "Перевірте G54/корекції та параметри лімітів ходу",
        "Perform reference return if required" to "За потреби виконайте повернення в референс",
        "Cabinet cooling issue" to "Проблема охолодження шафи",
        "Motor/amp thermal load" to "Теплове навантаження двигуна/підсилювача",
        "Blocked airflow or fan fault" to "Заблокований обдув або несправність вентилятора",
        "Inspect fans and filters" to "Перевірте вентилятори та фільтри",
        "Lower duty/load and monitor temperature" to "Зменште навантаження і контролюйте температуру",
        "Check ambient temperature and cabinet ventilation" to "Перевірте температуру довкілля та вентиляцію шафи",
        "APC battery low/zero" to "Низька або нульова напруга батареї APC",
        "Reference position lost" to "Втрачено референсну позицію",
        "Data/communication inconsistency" to "Невідповідність даних або зв'язку",
        "Check APC battery with machine-safe procedure" to "Перевірте батарею APC за безпечною процедурою",
        "Run reference return" to "Виконайте повернення в референс",
        "Verify detector/cable communication path" to "Перевірте канал зв'язку датчик/кабель",
        "Alarm category unclear from OCR/manual input" to "Категорію alarm не вдалося визначити з OCR/ручного вводу",
        "Controller-specific condition" to "Умова, специфічна для контролера",
        "Machine-builder ladder condition" to "Умова ladder логіки виробника верстата",
        "Capture full alarm line from CNC screen" to "Зніміть повний рядок alarm з екрана ЧПУ",
        "Retry with model/type selection" to "Повторіть із вибором моделі і типу",
        "Escalate with controller model + alarm screenshot" to "Передайте далі модель контролера + скрін alarm",
        "Detected CNC controller screen. Use AI Diagnostics to parse alarm text and resolve issue." to "Виявлено екран контролера ЧПУ. Використайте AI-діагностику для розбору alarm і вирішення проблеми.",
        "Detected machine nameplate/spec plate. Capture controller model and serial data for setup profile." to "Виявлено табличку верстата. Збережіть модель контролера та серійні дані для профілю наладки.",
        "Detected electrical schematic content. Verify voltage, relay chain and PLC I/O references." to "Виявлено електричну схему. Перевірте напругу, релейний ланцюг та посилання PLC I/O.",
        "Detected hydraulic scheme/context. Inspect pressure, valve states and pump condition." to "Виявлено гідравлічну схему. Перевірте тиск, стани клапанів і стан насоса.",
        "Detected part/tool photo. Use journal or tool database to save this process evidence." to "Виявлено фото деталі/інструмента. Використайте журнал або базу інструменту для збереження даних.",
        "Detected engineering drawing-style annotations. Use calculators/coordinates/thread reference for setup." to "Виявлено анотації креслення. Використайте калькулятори/координати/довідник різьб для наладки.",
        "Image analyzed but category is uncertain." to "Зображення проаналізовано, але категорію визначено невпевнено.",
        "Recognition failed:" to "Помилка розпізнавання:",
        "AI local diagnosis for" to "Локальна AI-діагностика для"
    )

    fun toUkrainian(source: String): String {
        var result = source
        glossary.forEach { (en, uk) ->
            result = result.replace(en, uk, ignoreCase = false)
        }
        return result
    }
}
